version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - save_cache:
          key: npm-cache
          paths:
            - /src/node_modules
  test:
    docker:
      - image: circleci/node:13.8.0
    step:
      - checkout
      - restore_cache:
        - key: npm-cache
      - run: npm run test
  analyze:
    docker:
      - image: circleci/node:13.8.0
    step:
      - checkout
      - restore_cache:
        - key: npm-cache
      - run: npm audit
workflows:
  npm-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
